# alacritty.toml
live_config_reload = true

[env]
TERM = "alacritty"

[window]
decorations     = "none"
dynamic_padding = false
dynamic_title   = true
opacity         = 1.0
startup_mode    = "Maximized"

[scrolling]
history = 12000

[font]
size = 15

[font.bold]
family = "JetBrains Mono"
style  = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style  = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style  = "Italic"

[font.normal]
family = "JetBrains Mono"
style  = "Regular"

[font.glyph_offset]
x = 0
y = 3

[selection]
save_to_clipboard     = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"